version: '3.7'

services:
  app:
    image: node:20-alpine

    command: sh -c "npm install && npm run dev"

    ports:
      - 3000:3000

    working_dir: /app

    volumes:
      - ./:/app
    
    environment:
      NEXT_PUBLIC_API: $NEXT_PUBLIC_API
      NEXT_PUBLIC_API_IMAGE: $NEXT_PUBLIC_API_IMAGE

    restart: always